services:
  postgres:
    restart: always
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_USER=robbo
      - POSTGRES_PASSWORD=robbo_pwd
      - POSTGRES_DB=robbo_db
    volumes:
      - postgres_data:/usr/lib/postgresql
    networks:
      postgres:
  app:
#    container_name: golang_container
    build: .
    environment:
      - DEBUG=false
      - POSTGRES_USER=robbo
      - POSTGRES_PASSWORD=robbo_pwd
      - POSTGRES_DB=robbo_db
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      postgres:
volumes:
  postgres_data: {}
networks:
  postgres:
    driver: bridge